#!/bin/bash

VERSION=$(curl -L -s http://nodejs.org/dist/latest/ | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' | tail -n1)
PLATFORM=linux
ARCH=x64
PREFIX="node-v$VERSION-$PLATFORM-$ARCH"
SRC="$HOME/src/$PREFIX"
TAR="$SRC.tar.gz"

if [ -z $(which node) ] || test "v$VERSION" != "$(node -v)"
then
  echo "Installing node v$VERSION ..."
  wget -O "$TAR" "http://nodejs.org/dist/v$VERSION/node-v$VERSION-$PLATFORM-$ARCH.tar.gz" &> /dev/null
  tar -zxf "$TAR" -C "$HOME/src" &> /dev/null
  rm -rf "$TAR"
  cd "$HOME/local"
  ln -sf "$SRC" node
else
  echo "Latest stable version of node already installed."
fi

cd $HOME
echo "$(which node)"
echo "$(node --version)"